workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.robotcontrol.app"
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android app
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - internal@codemagic.io
